### PR TITLE
Update the service for P4.

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Update the service for node version 4.

## Changes

Update the SDK version.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by abizjak** [comment]
> On protonet it says:
> 
> ```
> Error: Could not obtain last finalized block
> 
> Caused by:
>     0: RPC error: Error parsing JSON result: missing field `passiveReward`
>     1: Error parsing JSON result: missing field `passiveReward`
>     2: missing field `passiveReward`
> ```
> 
> On testnet it says:
> 
> ```
> 
> Error: Could not obtain last finalized block
> 
> Caused by:
>     0: RPC error: Error parsing JSON result: missing field `protocolVersion`
>     1: Error parsing JSON result: missing field `protocolVersion`
>     2: missing field `protocolVersion`
> ```
> 
> When starting up.

Yes, because the API of the node V3 and V4 are not compatible.

The version on protonet is additionally in a weird limbo variant which is not the same as a V3 node, nor is it the same as the latest V4 node (due to LPool and some other API renamings).

**Comment by abizjak** [comment]
> > On protonet it says:
> > ```
> > Error: Could not obtain last finalized block
> > 
> > Caused by:
> >     0: RPC error: Error parsing JSON result: missing field `passiveReward`
> >     1: Error parsing JSON result: missing field `passiveReward`
> >     2: missing field `passiveReward`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On testnet it says:
> > ```
> > 
> > Error: Could not obtain last finalized block
> > 
> > Caused by:
> >     0: RPC error: Error parsing JSON result: missing field `protocolVersion`
> >     1: Error parsing JSON result: missing field `protocolVersion`
> >     2: missing field `protocolVersion`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When starting up.
> 
> Yes, because the API of the node V3 and V4 are not compatible.
> 
> The version on protonet is additionally in a weird limbo variant which is not the same as a V3 node, nor is it the same as the latest V4 node (due to LPool and some other API renamings).

But on stagenet it works!

**Comment by abizjak** [comment]
@shjortConcordium I have updated this further after making some quality of life improvements to the SDK. Can you do another review?

**Review by shjortConcordium — APPROVED** [review]
LGTM, and works on stagenet!

**Pull request merged**
